### ISSUE TITLE
Use 100dvh instead of 100vh (min-h-screen)

### ISSUE THREAD

**Issue by mdmrk** [satnaing/astro-paper#127]
One advantage would be on mobile view where footer is not full visible. I don't think Tailwind supports it yet so I'll be using custom values meanwhile

https://github.com/satnaing/astro-paper/blob/cfcedd1418aa6ad512a5873d3df64b22d22ecb25/src/styles/base.css#L31-L34

```css
 body { 
   @apply flex min-h-[100dvh] flex-col bg-skin-fill font-mono text-skin-base  
   selection:bg-skin-accent selection:bg-opacity-70 selection:text-skin-inverted; 
 } 
```
