### ISSUE TITLE
How to configure so that when switching to light theme, the code highlight theme can also follow the switch?

### ISSUE THREAD

**Issue by hubingliang** [satnaing/astro-paper#32]

**Comment by satnaing** [comment]
Hello @hubingliang 
AstroPaper doesn't support "dynamic code theme changes on theme switches" out of the box.
AstroPaper uses the default syntax highlighter from `Shiki` which is also the default Syntax Highlighting Mode of [Astro's Markdown](https://docs.astro.build/en/guides/markdown-content/#syntax-highlighting).

If you want to achieve "dynamic syntax highlighting on theme switches", you can do the following. I think this is one of the easiest ways.

1. First, update `shikiConfig.theme` in `astro.config.mjs` to "css-variables"
```js
export default defineConfig({
  // other config ...
  markdown: {
    // other config ...
    shikiConfig: {
      theme: "css-variables",  // update this
      wrap: true,
    },
    extendDefaultPlugins: true,
  },
});
```

2. Then, inside `src/styles/base.css`, add your code block styles
```css
  :root,
  html[data-theme="light"] {
    --color-fill: 251, 254, 251;
    --color-text-base: 40, 39, 40;
    --color-accent: 0, 108, 172;
    --color-card: 230, 230, 230;
    --color-card-muted: 205, 205, 205;
    --color-border: 236, 233, 233;

    /* Code Block Styles for light theme */
    --astro-code-color-text: #000000;
    --astro-code-color-background: #d6d6d6;
    --astro-code-token-constant: #1c67d1;
    --astro-code-token-string: #e00000;
    --astro-code-token-comment: #eb0e0e;
    --astro-code-token-keyword: #e20808;
    --astro-code-token-parameter: #e40a0a;
    --astro-code-token-function: #d06b6b;
    --astro-code-token-string-expression: #33cc00;
    --astro-code-token-punctuation: #00cbdd;
    --astro-code-token-link: #ee00b2;
  }
  html[data-theme="dark"] {
    --color-fill: 33, 39, 55;
    --color-text-base: 234, 237, 243;
    --color-accent: 255, 107, 1;
    --color-card: 52, 63, 96;
    --color-card-muted: 138, 51, 2;
    --color-border: 171, 75, 8;

    /* Code Block Styles for dark theme */
    --astro-code-color-text: #eeeeee;
    --astro-code-color-background: #242424;
    --astro-code-token-constant: #1c67d1;
    --astro-code-token-string: #770000;
    --astro-code-token-comment: #880000;
    --astro-code-token-keyword: #990000;
    --astro-code-token-parameter: #aa0000;
    --astro-code-token-function: #bb0000;
    --astro-code-token-string-expression: #cc0000;
    --astro-code-token-punctuation: #dd0000;
    --astro-code-token-link: #ee0000;
  }
```

There may be other workarounds for this issue of course. You can also check out [shiki-themes docs](https://github.com/shikijs/shiki/blob/main/docs/themes.md#shiki-themes) for more info.

If you still have some problems, let me know. Hope this helps.
