### ISSUE TITLE
[BUG]: Code highlight for diffs doesn't work in light mode

### ISSUE THREAD

**Issue by alec-c4** [satnaing/astro-paper#498]
**Describe the bug**
When I use code highlighting for `diff` - it doesn't work in light mode, but works fine in dark mode.  

You can check it [here](https://alec-c4.com/posts/2025-04-02-kamal)

![Image](https://github.com/user-attachments/assets/a1aca497-27fa-4435-a310-9d76aefcdfc4)

![Image](https://github.com/user-attachments/assets/059f9d65-b36e-4b78-ad4f-9a587b250702)

**Comment by satnaing** [comment]
Hi, @alec-c4!

Starting from AstroPaper v5.4.0, we can have similar `diff` effect thanks to `transformerNotationDiff`.

From now on, you can do something like this

```yaml
service: super_duper_app # <-- the name of your app

image: apoimtsev/super_duper_app # <-- account and image name on hub.docker.com

# [!code --:3]
servers:
  web:
    - 191.168.1.1 # <-- server ip

# [!code --:3]
proxy:
  ssl: true
  host: super-duper.com # <-- hostname

registry:
  username: apoimtsev # <-- registry username
  password:
    - KAMAL_REGISTRY_PASSWORD

# [!code --:5]
env:
  secret:
    - RAILS_MASTER_KEY
  clear:
    SOLID_QUEUE_IN_PUMA: true

# [!code --:2]
volumes:
  - "super_duper_app_storage:/rails/storage" # <-- volume name

asset_path: /rails/public/assets

builder:
  arch: amd64
  args:
    RUBY_VERSION: <%= File.read(".ruby-version")[/(.*)/, 1] %>
    RAILS_MASTER_KEY: <%= File.read("config/master.key")[/(.*)/, 1] %>

ssh:
  user: deploy # <-- user on the server

aliases:
  console: app exec --interactive --reuse "bin/rails console"
  shell: app exec --interactive --reuse "bash"
  logs: app logs -f
  dbc: app exec --interactive --reuse "bin/rails dbconsole"
```

That will render something like this

![Image](https://github.com/user-attachments/assets/365c1207-aec9-4085-81b1-985f270bf1d1)

I'll close this issue as completed for now.
However, if you still experience issues with the latest AstroPaper, please reopen the issue.
